/**
 * Global constant
 */

export const FETCH_STATUS_NEVER = 'FETCH_STATUS_NEVER'
export const FETCH_STATUS_FETCHING = 'FETCH_STATUS_FETCHING'
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS'
export const FETCH_STATUS_FAIL = 'FETCH_STATUS_FAIL'

export const ATTACHMENT = {
  SORT_OLDEST_FIRST: 'SORT_OLDEST_FIRST',
  SORT_NEWEST_FIRST: 'SORT_NEWEST_FIRST',
  SORT_ATTACHMENT_AZ: 'SORT_ATTACHMENT_AZ',
  SORT_ATTACHMENT_ZA: 'SORT_ATTACHMENT_ZA',
  SORT_SMALLER_FIRST: 'SORT_SMALLER_FIRST',
  SORT_BIGGER_FIRST: 'SORT_BIGGER_FIRST',
  FILTER_ALL: 'FILTER_ALL',
  FILTER_IMAGES: 'FILTER_IMAGES',
  FILTER_DOCUMENTS: 'FILTER_DOCUMENTS',
  FILTER_AUDIOS: 'FILTER_AUDIOS',
  FILTER_VIDEOS: 'FILTER_VIDEOS',
  FILTER_ARCHIVES: 'FILTER_ARCHIVES',
}
